
services:
  client:
    image: joseluisq/static-web-server:2
    volumes:
      - ./client/Docker-Vite-Test/dist:/public
    ports:
      - 8080:80

  server:
    image: node:20-bookworm-slim
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    command: ["node", "/app/server.js"]
    volumes:
      - ./server/:/app/
    ports:
      - 3000:3000
